/**
 * @algochains/sdk — Auto-generated typed client for AlgoChains MCP Server v18.
 * Generated by: npx mcporter emit-ts algochains --mode client
 *
 * Usage:
 *   import { createAlgoChainsClient } from "@algochains/sdk";
 *   const ac = await createAlgoChainsClient();
 *   const regime = await ac.detectMarketRegime();
 */

export interface AlgoChainsClientOptions {
  /** MCPorter runtime instance (optional — created automatically if omitted) */
  runtime?: unknown;
  /** Server name in mcporter config (default: "algochains") */
  serverName?: string;
}

// ─── Smart Discovery ───────────────────────────────────────────────
export interface DiscoverToolsParams { query: string; category?: string; limit?: number; }
export type DiscoverToolsResult = Array<{ name: string; description: string; category: string; relevance: number; }>

export interface GetToolDetailsParams { name: string; }
export interface GetToolDetailsResult { name: string; description: string; inputSchema: Record<string, unknown>; annotations?: Record<string, unknown>; }

export interface ExecuteDynamicToolParams { name: string; arguments: Record<string, unknown>; }

// ─── Trading ───────────────────────────────────────────────────────
export interface PlaceOrderParams { broker: string; symbol: string; side: "buy" | "sell"; qty: number; order_type?: "market" | "limit" | "stop" | "stop_limit" | "trailing_stop"; limit_price?: number; stop_price?: number; }
export interface PlaceOrderResult { order_id: string; status: string; broker: string; symbol: string; filled_qty?: number; }

export interface CancelOrderParams { broker: string; order_id: string; }
export interface ClosePositionParams { broker: string; symbol: string; }
export interface CloseAllPositionsParams { broker: string; }
export interface GetPositionsParams { broker: string; }
export interface GetPositionsResult { positions: Array<{ symbol: string; qty: number; avg_price: number; unrealized_pnl: number; }>; }

export interface GetAccountParams { broker: string; }
export interface GetAccountResult { equity: number; cash: number; buying_power: number; broker: string; }

export interface PortfolioSummaryParams { broker?: string; }

// ─── V18 Intent Engine ─────────────────────────────────────────────
export interface ExecuteIntentParams { intent: string; dry_run?: boolean; risk_limit?: number; }
export interface ExecuteIntentResult { plan_id: string; intent: string; steps: Array<{ action: string; symbol?: string; qty?: number; }>; status: "pending" | "approved" | "executed"; }

export interface ApproveIntentParams { plan_id: string; }
export interface GetIntentHistoryResult { intents: Array<{ plan_id: string; intent: string; status: string; created_at: string; }>; }

export interface CreateShadowPortfolioParams { name: string; capital: number; strategy?: string; }
export interface GetShadowResultsParams { portfolio_id?: string; }

export interface EvolveStrategiesParams { action: "initialize" | "evaluate" | "evolve" | "get_top" | "get_unevaluated"; population_size?: number; }

export interface DetectArbitrageParams { symbols: string[]; }
export interface DetectArbitrageResult { scan_id: number; symbols_scanned: number; opportunities: Array<{ symbol: string; spread: number; brokers: string[]; }>; }

export interface DetectMarketRegimeResult { regime: "bull" | "bear" | "range" | "crisis"; confidence: number; signals_used: number; recommended_strategies: string[]; }

export interface PrefetchContextParams { symbols?: string[]; }

// ─── Massive White-Label Data ──────────────────────────────────────
export interface MassiveSearchEndpointsParams { query: string; scope?: "endpoints" | "functions" | "all"; }
export interface MassiveCallApiParams { method: "GET"; path: string; params?: Record<string, unknown>; store_as?: string; }
export interface MassiveQueryDataParams { sql: string; }
export interface MassiveRunPipelineParams { steps: Array<{ tool: string; params: Record<string, unknown>; }>; }

// ─── Strategy Pipeline ─────────────────────────────────────────────
export interface RunBacktestParams { strategy_id: string; start_date?: string; end_date?: string; }
export interface ValidateStrategyParams { spec: Record<string, unknown>; }
export interface OptimizeStrategyParams { strategy_id: string; param_grid?: Record<string, unknown>; }
export interface DeployStrategyParams { strategy_id: string; broker: string; mode?: "paper" | "live"; }
export interface BrowseStrategyMarketplaceParams { asset_class?: string; min_sharpe?: number; sort_by?: string; }

// ─── ML/GPU ────────────────────────────────────────────────────────
export interface DispatchGpuTaskParams { task_type: "training" | "inference" | "optimization" | "backtest"; payload: Record<string, unknown>; prefer_gpu?: "mac_m3" | "desktop_rtx" | "auto"; }
export interface GpuStatusResult { nodes: Array<{ name: string; device: string; available: boolean; utilization: number; }>; }

// ─── Analytics ──────────────────────────────────────────────────────
export interface DetectRegimeParams { symbol: string; }
export interface AnalyzeSentimentParams { symbol: string; }

// ─── Client Interface ──────────────────────────────────────────────
export interface AlgoChainsClient {
  // Smart Discovery
  discoverTools(params: DiscoverToolsParams): Promise<DiscoverToolsResult[]>;
  getToolDetails(params: GetToolDetailsParams): Promise<GetToolDetailsResult>;
  executeDynamicTool(params: ExecuteDynamicToolParams): Promise<unknown>;

  // Trading
  placeOrder(params: PlaceOrderParams): Promise<PlaceOrderResult>;
  cancelOrder(params: CancelOrderParams): Promise<{ success: boolean }>;
  closePosition(params: ClosePositionParams): Promise<{ success: boolean }>;
  closeAllPositions(params: CloseAllPositionsParams): Promise<{ success: boolean }>;
  getPositions(params: GetPositionsParams): Promise<GetPositionsResult>;
  getAccount(params: GetAccountParams): Promise<GetAccountResult>;
  portfolioSummary(params?: PortfolioSummaryParams): Promise<unknown>;

  // V18 Intent Engine
  executeIntent(params: ExecuteIntentParams): Promise<ExecuteIntentResult>;
  approveIntent(params: ApproveIntentParams): Promise<{ success: boolean }>;
  getIntentHistory(): Promise<GetIntentHistoryResult>;
  createShadowPortfolio(params: CreateShadowPortfolioParams): Promise<unknown>;
  getShadowResults(params?: GetShadowResultsParams): Promise<unknown>;
  evolveStrategies(params: EvolveStrategiesParams): Promise<unknown>;
  detectArbitrage(params: DetectArbitrageParams): Promise<DetectArbitrageResult>;
  detectMarketRegime(): Promise<DetectMarketRegimeResult>;
  prefetchContext(params?: PrefetchContextParams): Promise<unknown>;

  // Massive White-Label Data
  massiveSearchEndpoints(params: MassiveSearchEndpointsParams): Promise<unknown>;
  massiveCallApi(params: MassiveCallApiParams): Promise<unknown>;
  massiveQueryData(params: MassiveQueryDataParams): Promise<unknown>;
  massiveRunPipeline(params: MassiveRunPipelineParams): Promise<unknown>;

  // Strategy Pipeline
  runBacktest(params: RunBacktestParams): Promise<unknown>;
  validateStrategy(params: ValidateStrategyParams): Promise<unknown>;
  optimizeStrategy(params: OptimizeStrategyParams): Promise<unknown>;
  deployStrategy(params: DeployStrategyParams): Promise<unknown>;
  browseStrategyMarketplace(params?: BrowseStrategyMarketplaceParams): Promise<unknown>;

  // ML/GPU
  dispatchGpuTask(params: DispatchGpuTaskParams): Promise<unknown>;
  gpuStatus(): Promise<GpuStatusResult>;

  // Analytics
  detectRegime(params: DetectRegimeParams): Promise<unknown>;
  analyzeSentiment(params: AnalyzeSentimentParams): Promise<unknown>;

  // Platform
  getPlatformHealth(): Promise<{ status: string }>;
  brokerHealthCheck(): Promise<unknown>;
  checkRiskAlerts(params: { portfolio: Record<string, unknown> }): Promise<unknown>;

  // Generic call (for any tool by name)
  call(toolName: string, params?: Record<string, unknown>): Promise<unknown>;

  // Cleanup
  close(): Promise<void>;
}

export declare function createAlgoChainsClient(options?: AlgoChainsClientOptions): Promise<AlgoChainsClient>;
