/**
 * AlgoChains CLI — Config Management
 * ~/.algochains/config.toml is the single source of truth for all CLI settings.
 * Falls back to sensible defaults for every field.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import TOML from "toml";

export const CONFIG_DIR = join(homedir(), ".algochains");
export const CONFIG_FILE = join(CONFIG_DIR, "config.toml");
export const KILLSWITCH_FILE = join(CONFIG_DIR, "KILLSWITCH");
export const AUDIT_FILE = join(CONFIG_DIR, "audit.jsonl");
export const HISTORY_FILE = join(CONFIG_DIR, "history.jsonl");
export const TRIGGERS_FILE = join(CONFIG_DIR, "triggers.json");
export const DAEMON_PID_FILE = join(CONFIG_DIR, "daemon.pid");
export const DAEMON_PORT_FILE = join(CONFIG_DIR, "daemon.port");
export const DAEMON_TOKEN_FILE = join(CONFIG_DIR, "daemon.token");
export const DAEMON_LOG_FILE = join(CONFIG_DIR, "daemon.log");
export const CREDENTIALS_FILE = join(CONFIG_DIR, "credentials.toml");
export const PLUGINS_DIR = join(CONFIG_DIR, "plugins");
export const STATE_DIR = join(CONFIG_DIR, "state");

export interface Profile {
  mode: "demo" | "paper" | "live";
  tool_mode: "smart" | "full";
  broker?: string;
  daily_loss_limit?: number;
  require_confirm?: boolean;
  mcp_bridge_url?: string;
}

export interface CliConfig {
  default: { profile: string };
  profile: Record<string, Profile>;
  repl: {
    vim_mode: boolean;
    theme: "dark" | "light";
    regime_refresh_interval_ms: number;
    history_limit: number;
  };
  daemon: {
    port: number;
    auto_start: boolean;
  };
  telemetry: {
    enabled: boolean;
    endpoint?: string;
  };
  mcp: {
    bridge_url: string;
    timeout_ms: number;
  };
}

const DEFAULT_CONFIG: CliConfig = {
  default: { profile: "demo" },
  profile: {
    demo: {
      mode: "demo",
      tool_mode: "smart",
      mcp_bridge_url: "http://127.0.0.1:8090",
    },
    paper: {
      mode: "paper",
      tool_mode: "smart",
      broker: "alpaca_paper",
      daily_loss_limit: 500,
      mcp_bridge_url: "http://127.0.0.1:8090",
    },
    live: {
      mode: "live",
      tool_mode: "full",
      broker: "tradovate",
      daily_loss_limit: 500,
      require_confirm: true,
      mcp_bridge_url: "http://127.0.0.1:8090",
    },
  },
  repl: {
    vim_mode: false,
    theme: "dark",
    regime_refresh_interval_ms: 300_000, // 5 min
    history_limit: 1000,
  },
  daemon: {
    port: 39337,
    auto_start: false,
  },
  telemetry: {
    enabled: false,
  },
  mcp: {
    bridge_url: "http://127.0.0.1:8090",
    timeout_ms: 30_000,
  },
};

export function ensureConfigDir(): void {
  if (!existsSync(CONFIG_DIR)) mkdirSync(CONFIG_DIR, { recursive: true, mode: 0o700 });
  if (!existsSync(PLUGINS_DIR)) mkdirSync(PLUGINS_DIR, { recursive: true });
  if (!existsSync(STATE_DIR)) mkdirSync(STATE_DIR, { recursive: true });
}

export function loadConfig(): CliConfig {
  ensureConfigDir();
  if (!existsSync(CONFIG_FILE)) {
    writeDefaultConfig();
    return DEFAULT_CONFIG;
  }
  try {
    const raw = readFileSync(CONFIG_FILE, "utf-8");
    const parsed = TOML.parse(raw) as Partial<CliConfig>;
    // Deep merge with defaults
    return deepMerge(DEFAULT_CONFIG, parsed) as CliConfig;
  } catch {
    return DEFAULT_CONFIG;
  }
}

export function writeDefaultConfig(): void {
  const toml = `# AlgoChains CLI Configuration
# Generated by: algochains config init
# Edit this file to customize your CLI experience.

[default]
profile = "demo"

[profile.demo]
mode = "demo"
tool_mode = "smart"
mcp_bridge_url = "http://127.0.0.1:8090"

[profile.paper]
mode = "paper"
tool_mode = "smart"
broker = "alpaca_paper"
daily_loss_limit = 500
mcp_bridge_url = "http://127.0.0.1:8090"

[profile.live]
mode = "live"
tool_mode = "full"
broker = "tradovate"
daily_loss_limit = 500
require_confirm = true
mcp_bridge_url = "http://127.0.0.1:8090"

[repl]
vim_mode = false
theme = "dark"
regime_refresh_interval_ms = 300000
history_limit = 1000

[daemon]
port = 39337
auto_start = false

[telemetry]
enabled = false

[mcp]
bridge_url = "http://127.0.0.1:8090"
timeout_ms = 30000
`;
  writeFileSync(CONFIG_FILE, toml, { mode: 0o600 });
}

export function getActiveProfile(profileName?: string, config?: CliConfig): Profile {
  const cfg = config ?? loadConfig();
  const name = profileName ?? cfg.default.profile;
  return cfg.profile[name] ?? DEFAULT_CONFIG.profile.demo;
}

function deepMerge(base: Record<string, unknown>, override: Record<string, unknown>): Record<string, unknown> {
  const result = { ...base };
  for (const [k, v] of Object.entries(override)) {
    if (v && typeof v === "object" && !Array.isArray(v) && typeof result[k] === "object") {
      result[k] = deepMerge(result[k] as Record<string, unknown>, v as Record<string, unknown>);
    } else if (v !== undefined) {
      result[k] = v;
    }
  }
  return result;
}
